<?php
/**
 * Create by Skynix Team
 */
/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
$dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
?>   
<!-- ko scope: 'customer' -->
    <!-- ko ifnot: customer().fullname  -->
        <li class="authorization-link" style="display: inline-block" data-label="<?= $block->escapeHtml(__('or')) ?>">
            <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
                <?= $block->escapeHtml($block->getLabel()) ?>
            </a>
        </li>
    <!-- /ko -->
<!-- /ko -->
