<?php
/**
 * Create by Skynix Team
 */
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<!-- ko scope: 'customer' -->
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true">
            <!-- ko if: customer().fullname  -->
                <span data-bind="text: customer().fullname"></span>
                <button type="button"
                        class="action switch"
                        tabindex="-1"
                        data-action="customer-menu-toggle">
                    <span><?= $block->escapeHtml(__('Change')) ?></span>
                </button>
            <!-- /ko -->
        </span>
        <!-- ko if: customer().fullname  -->
            <?php if($block->getChildHtml()):?>
                <div class="customer-menu" data-target="dropdown">
                    <?= $block->getChildHtml() ?>
                </div>
        	<?php endif; ?>
        <!-- /ko -->
    </li>
<!-- /ko -->    
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}
</script>