<?php
/**
 * Create by Skynix Team
 */
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<li class="customer-welcome">
        <span class="customer-name huy"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
                <button type="button"
                        class="action switch"
                        tabindex="-1"
                        data-action="customer-menu-toggle">
                    <span><?= $block->escapeHtml(__('Change')) ?></span>
                </button>
            <!-- /ko -->
        </span>
    <!-- ko scope: 'customer' -->
        <!-- ko if: customer().fullname  -->
        <?php if ($block->getChildHtml()):?>
            <div class="customer-menu" data-target="dropdown">
                <?= $block->getChildHtml() ?>
            </div>
        <?php endif; ?>
        <!-- /ko -->
    <!-- /ko -->
</li>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customer": {
                    "component": "Magento_Customer/js/view/customer"
                }
            }
        }
    }
}
</script>
